### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by thelucyclub** [LostTeam/LostRealms#1]
So i'm working on another website, but it is still being tested. Is it possible for this banner code
```
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  <strong>(!)</strong> Try our new website design, <a class="link" href="https://lostrealmsweb.weebly.com">HERE</a>.
</div>
```
to be displayed at the top of the website? I've tried, and it doesn't seem to work. I didn't make the MC-Web-Template that was all @jasonwynn10  so I don't know exactly how to fix that. If anyone could help, that would be super. Thanks! 😃

**Comment by thelucyclub** [comment]
@jasonwynn10 any help? cmon man.

**Comment by jasonwynn10** [comment]
I do plugins, not java

**Comment by thelucyclub** [comment]
then who made the website template? also its hyper text markup language.

**Comment by MCUnderground** [comment]
When i wake up ill see what to do :) Fsst thing. Idk if i readed it correctly bc im tired. but you can use header tag in body tag

**Comment by jasonwynn10** [comment]
@thelucyclub i just found it online and modified it for easier editing

**Comment by jasonwynn10** [comment]
try using <header></header>

**Comment by thelucyclub** [comment]
@jasonwynn10 @MCUnderground 
I did. But, QQ can any of you get to this website?
It just redirects me to lostteam.tk/LostRealms , which doesn't exist.

**Comment by thelucyclub** [comment]
@jasonwynn10 @MCUnderground I tested offline and it still looks odd, plus you can't click on anything. :-/
